# Generated by Django 4.2.4 on 2023-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_profile_blood_group_profile_next_of_kin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="means_of_identity",
            field=models.ImageField(null=True, upload_to="identityImage/"),
        ),
    ]
