# Generated by Django 5.1.6 on 2025-02-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_profile_position_alter_profile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Surgery', 'Surgery'), ('Hematology', 'Hematology'), ('O & G', 'O & G'), ('paediatrics', 'Paediatrics'), ('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics')], max_length=50, null=True),
        ),
    ]
