# Generated by Django 4.2.4 on 2023-08-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=10, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=11, null=True, unique=True)),
                ("dob", models.CharField(max_length=11, null=True)),
                ("gender", models.CharField(max_length=11, null=True)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("United kingdom", "United Kingdom"),
                            ("USA", "USA"),
                            ("France", "France"),
                            ("Eygpt", "Eygpt"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Oyo", "Oyo"),
                            ("Ogun", "Ogun"),
                            ("Osun", "Osun"),
                            ("Lagos", "Lagos"),
                            ("Ekiti", "Ekiti"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "means_of_identity",
                    models.ImageField(
                        null=True, unique=True, upload_to="identityImage/"
                    ),
                ),
                (
                    "particulars",
                    models.ImageField(
                        null=True, unique=True, upload_to="particularsImage/"
                    ),
                ),
                (
                    "profile_passport",
                    models.ImageField(
                        null=True, unique=True, upload_to="profile_passport/"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CMD", "CMD"),
                            ("Consultunt", "Consultant"),
                            ("SR", "SR"),
                            ("HO", "HO"),
                            ("Admin", "Admin"),
                            ("Accountant", "Accountant"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Medicine", "Medicine"),
                            ("Surgery", "Surgery"),
                            ("Hematology", "Hematology"),
                            ("O & G", "O & G"),
                            ("paediatrics", "Paediatrics"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "maritalStatus",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widow", "Widow"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
