# Generated by Django 4.2.4 on 2023-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("B+", "B+"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("B-", "B-"),
                    ("O-", "O-"),
                    ("AB", "AB"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_of_kin",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
