# Generated by Django 4.2.4 on 2023-09-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_alter_profile_means_of_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="particulars",
            field=models.ImageField(null=True, upload_to="particularsImage/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_passport",
            field=models.ImageField(null=True, upload_to="profile_passport/"),
        ),
    ]
