# Generated by Django 4.2.4 on 2023-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service_option",
            field=models.CharField(
                choices=[
                    ("General Health", "General Health"),
                    ("Cardiology", "Cardiology"),
                    ("Dental", "Dental"),
                    ("Medicine", "Medicine"),
                    ("Neurology", "Neurology"),
                    ("Orthopaedics", "Orthopaedics"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
