# Generated by Django 4.2.4 on 2023-12-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_option",
                    models.CharField(
                        choices=[
                            ("General Health", "General Health"),
                            ("Cardiology", "Cardiology"),
                            ("Dental", "Dental"),
                            ("Neurology", "Neurology"),
                            ("Orthopaedics", "Orthopaedics"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("approved_time", models.TimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "doctors_remark",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
