# Generated by Django 4.2.4 on 2023-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_alter_profile_particulars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                choices=[
                    ("CMD", "CMD"),
                    ("Consultunt", "Consultant"),
                    ("SR", "SR"),
                    ("HO", "HO"),
                    ("HOD", "HOD"),
                    ("Admin", "Admin"),
                    ("Accountant", "Accountant"),
                    ("Medical Lab Scientist", "Medical Lab Scientist"),
                    ("Nurse", "Nurse"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="staff",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
