# Generated by Django 5.1.6 on 2026-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Medicine', 'Medicine'), ('Surgery', 'Surgery'), ('Hematology', 'Hematology'), ('O & G', 'O & G'), ('paediatrics', 'Paediatrics'), ('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics')], max_length=100, null=True),
        ),
    ]
