# Generated by Django 4.2.4 on 2025-02-19 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_option', models.CharField(choices=[('General Health', 'General Health'), ('Cardiology', 'Cardiology'), ('Dental', 'Dental'), ('Medicine', 'Medicine'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Surgery', 'Surgery'), ('Hematology', 'Hematology'), ('O & G', 'O & G'), ('paediatrics', 'Paediatrics')], max_length=20, null=True)),
                ('service_price', models.BigIntegerField()),
                ('service_description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('Hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
